package com.thetestingacademy;
import org.openqa.selenium.By;
import org.openqa.selenium.NoSuchElementException;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.FluentWait;
import org.openqa.selenium.support.ui.WebDriverWait;
import java.time.Duration;
import java.util.concurrent.TimeUnit;
import java.util.function.Function;
public class WaitHelpers {
    public static void waitJVM(int time) {
        try {
            Thread.sleep(time);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
    }
    public static void waitImplicitWait(WebDriver driver, int time) {
        driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(time));
    }
    public static void checkVisibility(WebDriver driver, By locator, int time) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));
        wait.until(ExpectedConditions.visibilityOfElementLocated(locator));
    }
    public static void checkVisibility(WebDriver driver, By locator) {
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
        wait.until(ExpectedConditions.visibilityOfElementLocated(locator));
    }
    public void checkVisibilityOfAndTextToBePresentInElement (WebDriver driver, String expectedText,By locator){
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(3));
        // Step 1: We use the locator to wait for visibility safely
        wait.until(ExpectedConditions.visibilityOfElementLocated(locator));
        // Step 2: We use the locator again to wait for the specific text
        wait.until(ExpectedConditions.textToBePresentInElementLocated(locator, expectedText));
    }
//Fluent wait is used very less
    public static WebElement checkVisibilityByFluentWait(WebDriver driver, By locator) {
        FluentWait<WebDriver> wait = new FluentWait<>(driver)
                .withTimeout(Duration.ofSeconds(10))
                .pollingEvery(Duration.ofSeconds(2)).ignoring(NoSuchElementException.class);
        WebElement error_message = wait.until(new Function<WebDriver, WebElement>() {
            public WebElement apply(WebDriver driver) {
                return driver.findElement(locator);
            }
        });
        return error_message;
    }
    public static void waitForAlert(WebDriver driver, int time){
        WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(time));
        wait.until(ExpectedConditions.alertIsPresent());
        /*When a website triggers a standard alert (usually via JavaScript, like a pop-up saying
         "Are you sure you want to delete this?"), that little gray box isn't made of HTML.
         It is a native pop-up generated by Chrome itself (or Edge, or Firefox).*/
    }
}
